#!/bin/sh
# Retrieve the ticket number from the branch name
# 1. Get name of current branch as refs/heads/<branch-name>
# 2. Cut '/' to retain only 3rd element
# 3. Grep for '<letters>[_-]<digits>'
# 4. Preserve only the first match of the previous pattern
# 5. Capitalize letters & replace '_' with '-'
ISSUE_NUMBER=$(git symbolic-ref HEAD | cut -d/ -f3 | grep -Eo "^[a-zA-Z]+[_-][0-9]+" | head -1 | tr "[a-z]_" "[A-Z]-")

# If the git commit message template (i.e. $1) does not contain the ticket name + number (happens when amending)
# then replace the first line, with the value extracted from the branch name
grep -q "$ISSUE_NUMBER" "$1" || sed -i -e '1 s/\(.*\)/'"$ISSUE_NUMBER"' : \1/' "$1"
