name: "Setup Maven"
description: "Setup JDK 17, maven cache, and JFrog credentials"

inputs:
  jfrog-user:
    description: JFrog username used to create the access key (password)
    required: true
  jfrog-password:
    description: JFrog access key (password)
    required: true

runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Checkout .github repository
      uses: actions/checkout@v3
      with:
        repository: energyhub/.github
        path: .github/
        ref: cat_49_remove_unapproved
    - name: Configure Maven
      shell: bash
      run: |
        sed "s/{username}/${{ inputs.jfrog-user }}/;s/{access_token}/${{ inputs.jfrog-password }}/"\
          .github/etc/ci/home_m2_settings.xml.template > $HOME/.m2/settings.xml
