name: "Setup Maven"
description: "Setup JDK (defaults to 17), Maven cache, and JFrog credentials."

inputs:
  jfrog-user:
    description: JFrog username used to create the access key (password)
    required: true
  jfrog-password:
    description: JFrog access key (password)
    required: true
  jdk-version:
    description: The JDK version to use
    default: "17"

runs:
  using: composite
  steps:
    - name: Set up JDK ${{ inputs.jdk-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.jdk-version }}
        distribution: "temurin"
        cache: "maven"
    - name: Generate settings.xml for Maven Builds
      shell: bash
      run: |
        sed "s/{username}/${{ inputs.jfrog-user }}/;s/{access_token}/${{ inputs.jfrog-password }}/"\
          ${GITHUB_ACTION_PATH}/home_m2_settings.xml.template > $HOME/.m2/settings.xml
