name: continuous integration

on:
  push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: continuous-integration

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Run tests
        run: make