# This workflow will automatically approve and enable auto-merge for pull requests created by dependabot.
# It will skip these actions for PRs which include a major version upgrade, as determined by semantic versioning.
# To use this in a repository, ensure the following:
#   1. "Allow auto-merge" is enabled https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository
#   2. At least one automated status check is required before merge. This is configured via branch protection rules.
name: Dependabot PR approval and auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: energyhub/workflow-auto-merge-dependabot/.github/workflows/workflow.yml@v1
    secrets: inherit
