name: Continuous Delivery

on:
  push:
    branches:
      - main

env:
  APP_REF: "jmt"                                     # set this to your service name / application reference
  APPLICATION_PATH: "server"                         # update this iff the application path from root differs
  JFROG_USER: "github-java-microservice-template"    # set this to the JFrog username used to create the access token
  # SLACK_PROD_DEPLOY_NOTIFY_WEBHOOK: ""             # uncomment and set to Slack webhook for prod deploy notifications
  # SLACK_FAILURE_NOTIFY_WEBHOOK: ""                 # uncomment and set to Slack webhook for deploy failure notifications

jobs:
  setup:
    # Workaround to make environment variables available to invocations of reusable workflows
    # https://github.community/t/reusable-workflow-env-context-not-available-in-jobs-job-id-with/206111
    name: Setup
    runs-on: ubuntu-24.04
    outputs:
      application-path: ${{ env.APPLICATION_PATH }}
      app-ref: ${{ env.APP_REF }}
      jfrog-user: ${{ env.JFROG_USER }}
      # slack-prod-deploy-webhook: ${{ env.SLACK_PROD_DEPLOY_NOTIFY_WEBHOOK }}
      # slack-failure-webhook: ${{ env.SLACK_FAILURE_NOTIFY_WEBHOOK }}
    steps:
      - run: exit 0

  maven-build-lifecycle:
    name: Build and Run Tests
    uses: energyhub/workflow-maven-build-lifecycle/.github/workflows/workflow.yml@v1
    needs: [ setup ]
    secrets: inherit
    with:
      jfrog-user: ${{ needs.setup.outputs.jfrog-user }}
      application-path: ${{ needs.setup.outputs.application-path }}
      upload-artifacts: true
      ecr-repository: energyhub/${{ needs.setup.outputs.app-ref }}

  continuous-deployment:
    needs: [ setup, maven-build-lifecycle ]
    name: Deploy service
    uses: energyhub/workflow-deploy-pipeline/.github/workflows/workflow.yml@v1
    secrets: inherit
    with:
      service: ${{ needs.setup.outputs.app-ref }}
      image-tag: ${{ needs.maven-build-lifecycle.outputs.image-tag }}
      # slack-prod-deploy-notify-webhook: ${{ needs.setup.outputs.slack-prod-deploy-webhook }}
      # slack-failure-notify-webhook: ${{ needs.setup.outputs.slack-failure-webhook }}
