name: Continuous Integration

on:
  push:

permissions:
  contents: read

jobs:
  maven-build-lifecycle:
    uses: energyhub/.github/.github/workflows/maven-build-lifecycle.yml@main
    secrets: inherit