name: Run Maven Build Lifecycle

on:
  workflow_call:
    secrets:
      JFROG_USER:
        required: true
      JFROG_PASSWORD:
        required: true
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true
      OCI_REGISTRY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
    inputs:
      upload-artifacts:
        required: true
        type: boolean

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    name: build-and-run-tests
    env:
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      OCI_REGISTRY: ${{ secrets.OCI_REGISTRY }}

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Copy maven settings
        run: cp etc/ci/home_m2_settings.xml $HOME/.m2/settings.xml

      - name: Build and Run tests
        run:  make

      - name: Upload server.jar
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: server/target/server-*.jar
          retention-days: 14
