name: Infrautils CFN Deploy

on:
  workflow_call:
    secrets:
      JFROG_CI_PASSWORD:
        required: true
    inputs:
      environment:
        required: true
        type: string
      service:
        description: "Name of the service to be deployed"
        required: true
        type: string
      image-tag:
        description: "Tag of the image to deploy"
        required: true
        type: string
      vpc:
        description: "VPC to deploy to, e.g. 'prod', 'qa-1', 'mec-rc', etc."
        required: true
        type: string

env:
  AWS_REGION: us-east-1

jobs:
  infrautils-cfn-deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    name: infrautils-cfn-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install infrautils
        run: |
          pip install infrautils \
            -i https://ci-infra-utils:"${{ secrets.JFROG_PASSWORD }}"@ehub.jfrog.io/artifactory/api/pypi/pypi-all/simple

      - name: Assume Actions IAM Role
        uses: energyhub/workflow-actions/assume-actions-role@v2.4.2

      - name: Deploy via Cloudformation
        run: |
          infrautils cfn.deploy \
            -p cloudformation/params/"${{ inputs.vpc }}"/"${{ inputs.service }}".yaml \
            -t cloudformation/templates/"${{ inputs.service }}".yaml \
            -e ImageTag="${{ inputs.image-tag }}"
