# This workflow installs infrautils (DevOps maintained infrastructure as service python package) from JFrog
# and uses infrautils (boto3) to deploy a EDX via cloudformation stack update
# https://github.com/energyhub/infra-utils
name: Infrautils CFN Deploy

on:
  workflow_call:
    secrets:
      JFROG_PYPI_PASSWORD:
        required: true
    inputs:
      image-tag:
        description: "Tag of the image to deploy"
        required: true
        type: string
      vpc:
        description: "VPC to deploy to, e.g. 'prod', 'qa-1', 'mec-rc', etc."
        required: true
        type: string

env:
  JFROG_PYPI_URI: ehub.jfrog.io/artifactory/api/pypi/pypi-all/simple

permissions:
  contents: read
  id-token: write

jobs:
  infrautils-cfn-deploy:
    runs-on: ubuntu-latest
    name: infrautils-EDX-cfn-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install infrautils
        run: |
          pip install infrautils \
            -i https://ci-infra-utils:${{ secrets.JFROG_PYPI_PASSWORD }}@${{ env.JFROG_PYPI_URI }}
      - name: Assume Actions IAM Role
        uses: energyhub/workflow-actions/assume-actions-role@v2.4.2

      - name: Deploy via Cloudformation
        run: |
          infrautils cfn.deploy \
            -s ${{ inputs.vpc }}-edx-ecs-tasks-and-services \
            -e Env=${{ inputs.vpc }} \
            -e ctpImageTag=${{ inputs.image-tag }} \
            -e EnrollmentWorkerImageTag=${{ inputs.image-tag }} \
            -e WorkhorseImageTag=${{ inputs.image-tag }} \
            -e oadrvtnImageTag=${{ inputs.image-tag }} \
            -e uwpImageTag=${{ inputs.image-tag }} \
            -e ReportsImageTag=${{ inputs.image-tag }} \
            -e PartnerAPIImageTag=${{ inputs.image-tag }} \
            -e Sep2UtilityImageTag=${{ inputs.image-tag }} \
            -e DeploymentRegister=$(date --iso-8601=seconds)
