# This workflow installs infrautils (DevOps maintained infrastructure as service python package) from JFrog
# and uses infrautils (boto3) to deploy a cloudformation stack update
# directly from the ecs-alb generic microservice template in S3
# https://github.com/energyhub/infra-utils
name: Infrautils CFN Deploy

on:
  workflow_call:
    secrets:
      JFROG_PYPI_PASSWORD:
        required: true
    inputs:
      environment:
        required: false
        type: string
      service:
        description: "Name of the service to be deployed"
        required: true
        type: string
      image-tag:
        description: "Tag of the image to deploy"
        required: true
        type: string
      vpc:
        description: "VPC to deploy to, e.g. 'prod', 'qa-1', 'mec-rc', etc."
        required: true
        type: string
      template-path:
        description: "The path to the template file inside of the cloudformation project"
        required: false
        type: string
        default: "microservices/ecs-alb-microservice.yaml"
      parameter-overrides:
        description: "Any additional parameter overrides, e.g. '-e DesiredTasks=6 -e TaskMem=4096'"
        type: string
        required: false

env:
  JFROG_PYPI_URI: ehub.jfrog.io/artifactory/api/pypi/pypi-all/simple

permissions:
  contents: read
  id-token: write

jobs:
  infrautils-cfn-deploy-without-environment:
    if: inputs.environment == ''
    runs-on: ubuntu-latest
    name: infrautils-cfn-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install infrautils
        run: |
          pip install infrautils \
            -i https://ci-infra-utils:${{ secrets.JFROG_PYPI_PASSWORD }}@${{ env.JFROG_PYPI_URI }}

      - name: Assume Actions IAM Role
        uses: energyhub/workflow-actions/assume-actions-role@v2.4.2

      - name: Deploy via Cloudformation
        run: |
          infrautils cfn.deploy \
            -s ${{ inputs.vpc }}-${{ inputs.service }} \
            -t https://infradata.s3.amazonaws.com/cloudformation/templates/${{ inputs.template-path }} \
            -r deploy-${{ inputs.service }}-role \
            -e Env=${{ inputs.vpc }}  \
            -e ImageTag=${{ inputs.image-tag }} \
            -e AppRef=${{ inputs.service }} \
            -e DeploymentRegister=$(date --iso-8601=seconds) \
            ${{ inputs.parameter-overrides }}

  infrautils-cfn-deploy-with-environment:
    if: inputs.environment != ''
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    name: infrautils-cfn-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install infrautils
        run: |
          pip install infrautils \
            -i https://ci-infra-utils:${{ secrets.JFROG_PYPI_PASSWORD }}@${{ env.JFROG_PYPI_URI }}

      - name: Assume Actions IAM Role
        uses: energyhub/workflow-actions/assume-actions-role@v2.4.2

      - name: Deploy via Cloudformation
        run: |
          infrautils cfn.deploy \
            -s ${{ inputs.vpc }}-${{ inputs.service }} \
            -t https://infradata.s3.amazonaws.com/cloudformation/templates/${{ inputs.template-path }} \
            -r deploy-${{ inputs.service }}-role \
            -e Env=${{ inputs.vpc }}  \
            -e ImageTag=${{ inputs.image-tag }} \
            -e AppRef=${{ inputs.service }} \
            -e DeploymentRegister=$(date --iso-8601=seconds) \
            ${{ inputs.parameter-overrides }}
