name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Validate PR title
        uses: energyhub/action-validate-pr-title@v1
        with:
          regex: '^[A-Z]+-\d+\s?:\s.*$'
          ignored_branch_prefixes: 'dependabot'